name: Compilar fornecedores-service

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
          cache-dependency-path: fornecedores-service/pom.xml

      - name: Compilar com Maven
        working-directory: fornecedores-service
        run: mvn --batch-mode clean verify
